/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionNewRouteImport } from './routes/mission.new'
import { Route as MissionMissionIdRouteImport } from './routes/mission.$missionId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionNewRoute = MissionNewRouteImport.update({
  id: '/mission/new',
  path: '/mission/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMissionIdRoute = MissionMissionIdRouteImport.update({
  id: '/mission/$missionId',
  path: '/mission/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/missions': typeof MissionsRoute
  '/verify': typeof VerifyRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/mission/new': typeof MissionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/missions': typeof MissionsRoute
  '/verify': typeof VerifyRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/mission/new': typeof MissionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/missions': typeof MissionsRoute
  '/verify': typeof VerifyRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/mission/new': typeof MissionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/missions'
    | '/verify'
    | '/agents/$agentId'
    | '/mission/$missionId'
    | '/mission/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/missions'
    | '/verify'
    | '/agents/$agentId'
    | '/mission/$missionId'
    | '/mission/new'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/missions'
    | '/verify'
    | '/agents/$agentId'
    | '/mission/$missionId'
    | '/mission/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  VerifyRoute: typeof VerifyRoute
  MissionMissionIdRoute: typeof MissionMissionIdRoute
  MissionNewRoute: typeof MissionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/new': {
      id: '/mission/new'
      path: '/mission/new'
      fullPath: '/mission/new'
      preLoaderRoute: typeof MissionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$missionId': {
      id: '/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof MissionMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  MissionsRoute: MissionsRoute,
  VerifyRoute: VerifyRoute,
  MissionMissionIdRoute: MissionMissionIdRoute,
  MissionNewRoute: MissionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
